--------------------------------------------------------------------------
--									--
--									--
--				ctrl.lua				--
--									--
--									--
--------------------------------------------------------------------------
print( "Loading Puzzleworld2 Ctrl.lua" )


function config(map)
    MapCanSavePos(map, 0)		-- 1 = Allow players to save respaw // 0 = Do not allow players to save respaw
    MapCanPK(map, 1)			-- 1 = Turns on PK Mouse Sword Icon // 0 = Turns off PK Mouse Sword Icon ( Need to press CTRL key )
    MapCopyNum(map, 1)			-- 1 Copy of the map will be generated by GameServer
    SingleMapCopyPlyNum(map, 300)	-- 300 Players are allowed to enter the map 
    MapCanTeam(map , 1)			-- 1 = Allow players to create party // 0 = Do not allow Players to create party
    MapType ( map , 4 )			-- 0 = PvP Off // 1 = PvP Off // 2 = PvP On ( Not allowed to kill Guild and Party Mates ) // 3 = PvP On ( Allowed to kill any player but not Party Mates ) // 4 = PvP On ( Not allowed to kill Guild and Party Mates )        
end

function get_map_entry_pos_puzzleworld2()

	local POS_X=172
	local POS_Y=165
	local a = 100
	local k = math.random ( 1 , a )
	if k < 25 then
		POS_X = 172
		POS_Y = 165
	end
	if k >= 25 and k < 50 then
		POS_X = 147
		POS_Y = 384
	end
	if k >= 50 and k < 75 then
		POS_X = 365
		POS_Y = 381
	end
	if k >= 75 then
		POS_X = 365
		POS_Y = 171
	end
	
	return POS_X , POS_Y

end

function init_entry(map)
    SetMapEntryMapName(map, "puzzleworld")
    SetMapEntryTime(map, "2008/8/30/0/0", "0/3/0", "0/1/0", "0/2/0")	-- The first set of numbers is the starting point (Year/Month/Day/Hour/Minute), next is opening interval (Day/Hour/Minute), portal open duration (Day/Hour/Minute), and last is the map duration (Day/Hour/Minute)

end